spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.acks=1
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
server.port=${SERVER_PORT:0}

app.transport.mode=${APP_TRANSPORT_MODE:kafka}

app.kafka.client-id=${KAFKA_CLIENT_ID:motion-event-producer}
app.kafka.topics.position=${KAFKA_TOPIC_POSITION:motion-position}
app.kafka.topics.collision=${KAFKA_TOPIC_COLLISION:motion-collision}

app.websocket.url=${APP_WEBSOCKET_URL:ws://localhost:8080/ws/events}
app.websocket.reconnect-ms=${APP_WEBSOCKET_RECONNECT_MS:2000}

app.gateway.websocket.path=${APP_GATEWAY_WEBSOCKET_PATH:/ws/events}
